### ISSUE TITLE
Warning on "Home" page

### ISSUE THREAD

**Issue by StayOx** [nineteeneleven/Donations-Control#1]
Warning: date() expects parameter 2 to be long, string given in .../donations/admin/pages/list.php on line 72

**Comment by nineteeneleven** [comment]
Im not seeing that. Make sure there are no empty values for sign_up_date, expiration_date or renewal_date in the database.

**Comment by StayOx** [comment]
This bug occurs only in "Manual Entries" why not set a default value for  renewal_date on database.

Entries via Paypal the script determines the default value for renewal_date to Never and the bug does not happen
