### ISSUE TITLE
Impossible Remove User

### ISSUE THREAD

**Issue by StayOx** [nineteeneleven/Donations-Control#2]
Hello, I noticed a small problem, however strange.

Users with this: ' at the end of Steam Name becomes impossible to remove it from the system using the Donor Control.

Eg: Steam Name = James'''''' 'or James'

**Comment by nineteeneleven** [comment]
Fixed in the latest commit

**Comment by StayOx** [comment]
hey guy, see this

Donor List -  http://s10.postimg.org/br6p3yq6h/painel_error.png 
Bans - http://s22.postimg.org/ay62ykn4h/noname_bans.png
Database - http://s22.postimg.org/5j708gr9t/noinfo_db.png

After making the last fixes the donor list lost some information, SteamID, SteamName, and SourceBans  the username is not saved

**Comment by nineteeneleven** [comment]
I got a little out of hand with the $mysqli->real_escape_string and accidently wrapped the array that is retured with all the users information. Only manual entries look like they were effected.

edit: and edit users. ill push the update now.
