### ISSUE TITLE
Steam ID's with invalid formats.

### ISSUE THREAD

**Issue by StayOx** [nineteeneleven/Donations-Control#3]
Hello, I realized that it is possible to make donations using SteamID with invalid formats. The warning "You probably Entered an incorrect Steam ID" does not appear

e.g.: @ kjsf bf7763876t3478r27  or  STEAM_9:9:FAKEID

see - http://s11.postimg.org/90stgoj7n/fake_id.png - Donor Page

http://s18.postimg.org/4fl8j6dqx/dc_id.png  -  Donor Control

**Comment by nineteeneleven** [comment]
Unless it is a url it doesn't verify with steam servers. I will fix it, but
it isn't a priority Espically if your using the player tracker plugin.

**Comment by nineteeneleven** [comment]
Well it's not a priority because I want to finish the localizations first

**Comment by StayOx** [comment]
ok no problem. but is possible made a donation using - google.com , cnn.com or fake Steam Url´s  e.g - steamcommunity.com/id/fggg/google/@@@/FAKEUSER

and location formats for DATE/TIME would be cool..

**Comment by nineteeneleven** [comment]
Will now always verify with steam.
