### ISSUE TITLE
Select Language Button

### ISSUE THREAD

**Issue by StayOx** [nineteeneleven/Donations-Control#5]
Hello guy, there is a small problem in language selection button, missing the option: "Select" No it is not possible to select the language Speak 1337

note:

I updated my fork of Donor Control, I added 5 new messages and updated translation languages​​, fix a small problem with the log in show_donations.php, added the file:  pt-br.json (Portuguese Brazilian translation)  updated /includes/config.php I will soon add the Spanish translation. 

Please, check all changes and update your main repo

I do not like GitHub, the interface is complicated XD ......

**Comment by nineteeneleven** [comment]
it works just fine, It uses javascript to auto refresh the page. you can see it on my test site at http://nineteeneleven.info

**Comment by StayOx** [comment]
lol working now lol
