### ISSUE TITLE
Google Chrome charset utf8

### ISSUE THREAD

**Issue by StayOx** [nineteeneleven/Donations-Control#6]
There is a small problem with utf-8 charset in the message "Invalid Steam ID" in the Google Chrome browser
![chrome_error](https://f.cloud.github.com/assets/5573178/1535355/b27a3f74-4ca2-11e3-82cc-b3be68d10fad.png)

**Comment by nineteeneleven** [comment]
It's because it's wrapped in a die statement and doesn't have the meta tag

**Comment by StayOx** [comment]
I will seek a solution.
